export const PDF_LIST_REQUEST = "PDF_LIST_REQUEST";
export const PDF_LIST_SUCCESS = "PDF_LIST_SUCCESS";
export const PDF_LIST_FAIL = "PDF_LIST_FAIL";

export const PDF_EDIT_REQUEST = "PDF_EDIT_REQUEST";
export const PDF_EDIT_SUCCESS = "PDF_EDIT_SUCCESS";
export const PDF_EDIT_FAIL = "PDF_EDIT_FAIL";

export const PDF_DELETE_REQUEST = "PDF_DELETE_REQUEST";
export const PDF_DELETE_SUCCESS = "PDF_DELETE_SUCCESS";
export const PDF_DELETE_FAIL = "PDF_DELETE_FAIL";

export const PDF_CREATE_REQUEST = "PDF_CREATE_REQUEST";
export const PDF_CREATE_SUCCESS = "PDF_CREATE_SUCCESS";
export const PDF_CREATE_FAIL = "PDF_CREATE_FAIL";
export const PDF_CREATE_RESET = "PDF_CREATE_RESET";

export const PDF_UPDATE_REQUEST = "PDF_UPDATE_REQUEST";
export const PDF_UPDATE_SUCCESS = "PDF_UPDATE_SUCCESS";
export const PDF_UPDATE_FAIL = "PDF_UPDATE_FAIL";
export const PDF_UPDATE_RESET = "PDF_UPDATE_RESET";
