export const PDF_LIST_REQUEST = "PDF_LIST_REQUEST";
export const PDF_LIST_SUCCESS = "PDF_LIST_SUCCESS";
export const PDF_LIST_FAIL = "PDF_LIST_FAIL";

export const PDF_DETAILS_REQUEST = "PDF_DETAILS_REQUEST";
export const PDF_DETAILS_SUCCESS = "PDF_DETAILS_SUCCESS";
export const PDF_DETAILS_FAIL = "PDF_DETAILS_FAIL";

export const PDF_CREATE_REVIEW_REQUEST = "PDF_CREATE_REVIEW_REQUEST";
export const PDF_CREATE_REVIEW_SUCCESS = "PDF_CREATE_REVIEW_SUCCESS";
export const PDF_CREATE_REVIEW_FAIL = "PDF_CREATE_REVIEW_FAIL";
export const PDF_CREATE_REVIEW_RESET = "PDF_CREATE_REVIEW_RESET";
